include theme.conf

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #0d1b2a
active_tab_background   #5dade2
active_tab_font_style   bold
inactive_tab_foreground #c8d6e5
inactive_tab_background #1b2838
inactive_tab_font_style normal
tab_bar_background      #0a1520
