# Dark theme (GitHub Dark High Contrast)
background #0A0C10
foreground #F0F3F6
cursor #F0F3F6
cursor_text_color #0A0C10
selection_background #409EFF
selection_foreground #FFFFFF
color0  #7A828E
color8  #9EA7B3
color1  #FF6A69
color9  #FF9492
color2  #26CD4D
color10 #4AE168
color3  #F0B72F
color11 #F7C843
color4  #71B7FF
color12 #91CBFF
color5  #CB9EFF
color13 #DBB7FF
color6  #39C5CF
color14 #56D4DD
color7  #D9DEE3
color15 #FFFFFF

# Tab bar
active_tab_foreground   #0A0C10
active_tab_background   #71B7FF
inactive_tab_foreground #9EA7B3
inactive_tab_background #272B33
tab_bar_background      #0A0C10
