unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g prefix C-s
set -g mouse on

# Move between panes
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R

# Light theme status bar
set -g status-style bg=#ECEFF4,fg=#2E3440
set -g status-left-style bg=#ECEFF4,fg=#2E3440
set -g status-right-style bg=#ECEFF4,fg=#2E3440
set -g window-status-style bg=#ECEFF4,fg=#2E3440
set -g window-status-current-style bg=#D08770,fg=#ECEFF4,bold
set -g pane-border-style fg=#4C7086
set -g pane-active-border-style fg=#0184BC

